#!groovy

// Generated by IBM TransformationAdvisor
// Thu Oct 25 18:09:11 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}