#!groovy

// Generated by IBM TransformationAdvisor
// Fri Nov 02 13:32:40 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}