#!groovy

// Generated by IBM TransformationAdvisor
// Fri Nov 09 15:42:53 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}